name: Test

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        run: |
          rustup update stable
          rustup component add rustfmt --toolchain stable
      - name: Check formatting
        run: cargo fmt --all -- --check
  
  clippy:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        run: |
          rustup update stable
          rustup component add clippy --toolchain stable
      - name: Run clippy
        run: cargo clippy --locked --all-targets -- -D warnings

  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        run: rustup update stable
      - name: Install LLVM 22
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            llvm-22 \
            llvm-22-dev \
            clang-22 \
            libclang-22-dev \
            libclang-cpp22-dev
      - name: Build wasm2c
        run: RUSTFLAGS="-Dwarnings" cargo +stable build --locked --all
      - name: Test wasm2c
        run: RUSTFLAGS="-Dwarnings" cargo +stable test --locked --all -- --no-capture
